# NumPy Broadcasting - Efficient Array Operations

Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations. This notebook demonstrates:
- Basic vectorized operations
- Broadcasting rules and mechanics
- Real-world applications (data normalization, image processing)
- Performance benefits over loops

**Key Concept:** Broadcasting extends smaller arrays across larger ones without copying data, making operations both memory-efficient and fast.

## 1. Vectorized Operations - The Foundation

Vectorized operations apply functions to entire arrays at once, eliminating the need for Python loops:

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = arr ** 2 # Vectorized operation
print(result) 

[ 1  4  9 16 25]


In [3]:
result + 10


array([11, 14, 19, 26, 35])

## 2. Broadcasting with Different Shapes

Broadcasting automatically expands arrays to compatible shapes:

In [4]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])

result = arr1 + arr2  # Broadcasting arr2 across arr1

print(result)

[[2 4 6]
 [5 7 9]]


In [ ]:
# Visualizing the broadcasting
print("arr1 shape:", arr1.shape)  # (2, 3)
print("arr2 shape:", arr2.shape)  # (3,)
print("\nBroadcasting arr2 across each row of arr1:")
print(f"arr1:\n{arr1}")
print(f"\narr2: {arr2}")
print(f"\nResult:\n{result}")

In [5]:
# Simulating a dataset (5 samples, 3 features)

data = np.array([[10, 20, 30],
[15, 25, 35],
[20, 30, 40],
[25, 35, 45],
[30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

# Normalizing the data using broadcasting
normalized_data = (data - mean) / std
print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]


## 3. Applications

In [8]:

# Example 1: Adding a bias term to each column
matrix = np.array([[1, 2, 3], [4, 5, 6]])
bias = np.array([[10], [20]])  # Column vector
result = matrix + bias
print("\nMatrix with bias:\n", result)

# Example 2: Outer product using broadcasting
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30])
outer = a[:, np.newaxis] * b[np.newaxis, :]
print("\nOuter product:\n", outer)


Matrix with bias:
 [[11 12 13]
 [24 25 26]]

Outer product:
 [[ 10  20  30]
 [ 20  40  60]
 [ 30  60  90]
 [ 40  80 120]]
