# NumPy Indexing and Slicing

Master the art of accessing and manipulating array elements efficiently:
- **Basic indexing:** Accessing individual elements
- **Slicing:** Extracting subarrays
- **Boolean indexing:** Filtering based on conditions
- **Fancy indexing:** Using arrays as indices

These techniques are fundamental for data manipulation and analysis.

## 1. Basic Indexing

Access individual elements using zero-based indexing:

In [2]:
import numpy as np

arr = np.array([10, 20, 30, 40])
print(arr[0]) 
print(arr[-1]) 

10
40


## 2. Array Slicing

Extract subarrays using the slice notation `start:stop:step`:

In [7]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])  #(slice from index 1 to 3)
print(arr[:3])  #(first 3 elements)
print(arr[::2])  #(every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [ ]:
## 3. Boolean Indexing (Conditional Selection)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Modify single element
arr[0] = 100
print("After modifying first element:", arr)

# Modify multiple elements with slicing
arr[1:4] = [20, 30, 40]
print("After modifying slice:", arr)

# Modify using boolean indexing (cap values at 50)
arr[arr > 50] = 50
print("After capping at 50:", arr)

# Replace negative values with zero
data = np.array([10, -5, 20, -3, 15])
data[data < 0] = 0
print("\nAfter replacing negatives with 0:", data)

## 5. Modifying Array Values

In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60])

# Select specific indices
indices = [0, 2, 4]
print("Elements at indices 0, 2, 4:", arr[indices])

# Reorder elements
print("Reversed order:", arr[[5, 4, 3, 2, 1, 0]])

# 2D fancy indexing
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = [0, 2]
cols = [1, 2]
print("\nSelected elements from matrix:", matrix[rows, cols])  # Elements at (0,1) and (2,2)

## 4. Fancy Indexing (Array Indexing)

In [ ]:
arr = np.array([10, 25, 30, 45, 50, 15])

# Create a boolean mask
mask = arr > 25
print("Boolean mask:", mask)
print("Values > 25:", arr[mask])

# Multiple conditions (use & for AND, | for OR)
print("Values between 20 and 40:", arr[(arr > 20) & (arr < 40)])

# Practical example: filtering data
temperatures = np.array([22, 28, 19, 35, 40, 25, 18])
hot_days = temperatures[temperatures > 30]
print(f"\nHot days (>30°C): {hot_days}")