# Multidimensional Arrays in NumPy

Explore working with 2D, 3D, and higher-dimensional arrays:
- **Matrix operations:** Working with 2D arrays
- **Axis operations:** Understanding axis parameter
- **3D arrays:** Handling multi-layered data


## 1. Creating 2D Arrays (Matrices)

In [2]:
import numpy as np

arr = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(np.sum(arr, axis=0)) # Sum along rows (down each column)
print(np.sum(arr, axis=1)) # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [ ]:
# More axis examples
print("Mean across rows (each column):", np.mean(arr, axis=0))
print("Mean across columns (each row):", np.mean(arr, axis=1))
print("Max in each row:", np.max(arr, axis=1))
print("Min in each column:", np.min(arr, axis=0))

## 2. Understanding Axis Operations

The `axis` parameter determines the dimension along which an operation is performed:
- **axis=0:** Operations down rows (column-wise)
- **axis=1:** Operations across columns (row-wise)
- **axis=None:** Operation on entire array

In [6]:
arr[0:1]

array([[1, 2, 3]])

## 3. 2D Array Slicing

In [15]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [16]:
# More slicing examples
print("First column:", arr[:, 0])
print("Last row:", arr[-1, :])
print("Center element:", arr[1, 1])
print("Every other row:", arr[::2, :])

First column: [1 4 7]
Last row: [7 8 9]
Center element: 5
Every other row: [[1 2 3]
 [7 8 9]]


In [17]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)

print(arr3D.shape) # Output: (2, 2, 3)
print(arr3D)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 4. Working with 3D Arrays

3D arrays can be thought of as "stacks of matrices" or "multiple sheets":
- **Dimension 0 (depth):** Which sheet/layer
- **Dimension 1 (rows):** Which row in that sheet
- **Dimension 2 (columns):** Which column in that row

In [13]:
#First sheet, second row, third column
print(arr3D[0, 1, 2]) 

print(arr3D[:, 0, :]) # Get the first row from both sheets


6
[[1 2 3]
 [7 8 9]]


In [14]:
 #Get all rows of the first column
first_col = arr[:, 0]
print(first_col)

# Get the first row from each "sheet" in a 3D array
first_rows = arr3D[:, 0, :]
print(first_rows)

[1 4 7]
[[1 2 3]
 [7 8 9]]
