# NumPy Arrays - Comprehensive Guide

This notebook covers the fundamentals of creating and manipulating NumPy arrays, including:
- Array creation methods
- Array properties and attributes
- Data type handling

NumPy (Numerical Python) is the foundation of scientific computing in Python, providing powerful N-dimensional array objects and functions for working with these arrays.

## 1. Array Creation Methods

NumPy provides various ways to create arrays:

In [3]:
import numpy as np


In [ ]:
# Creating a simple 1D array from a Python list
arr = np.array([1, 3, 5])
print("Array:", arr)
print("Type:", type(arr))

### Creating arrays filled with zeros, ones, or custom values

In [6]:
arr


array([1, 3, 5])

In [ ]:
# Create a 3x4 matrix filled with zeros
zeros_matrix = np.zeros((3, 4))
print("Zeros matrix:\n", zeros_matrix)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Create a 2x5 matrix filled with ones
ones_matrix = np.ones((2, 5))
print("Ones matrix:\n", ones_matrix)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Create a 4x6 matrix filled with a custom value (8)
custom_matrix = np.full((4, 6), 8)
print("Custom filled matrix:\n", custom_matrix)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [ ]:
# Create a 5x5 identity matrix (diagonal of 1s)
identity = np.eye(5)
print("Identity matrix:\n", identity)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Creating sequences and ranges

In [ ]:
# Create a range of odd numbers from 1 to 99
odd_numbers = np.arange(1, 100, 2)
print("Odd numbers:", odd_numbers)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [14]:
np.linspace(0, 1, 5) # [0. 0.25 0.5 0.75 1.] (evenly spaced)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Random arrays for simulations

In [15]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape) # (2, 3) → 2 rows, 3 columns

print("Size:", arr.size)

print("Dimensions:", arr.ndim) # 2 → 2D array
# 6 → total elements
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


## 2. Array Properties and Attributes

Understanding array properties is essential for effective data manipulation:

In [16]:
arr = np.array([1, 2, 3], dtype=np.float32) # Explicit type

print(arr.dtype) # float32

arr_int = arr.astype(np.int32) # Convert float to int

print(arr_int) # [1 2 3]

float32
[1 2 3]


## 3. Data Type Conversion

Choosing the right data type can significantly impact memory usage and computation speed:

In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) 

reshaped = arr.reshape((3, 2)) # Change shape
print(reshaped)

flattened = arr.flatten() # Convert 2D → 1D
print(flattened) 

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [ ]:
# Transpose: swap rows and columns
transposed = arr.T
print("Transposed:\n", transposed)

# Stack arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

vstacked = np.vstack([arr1, arr2])  # Vertical stack
print("\nVertically stacked:\n", vstacked)

hstacked = np.hstack([arr1, arr2])  # Horizontal stack
print("\nHorizontally stacked:", hstacked)